const replace = {
	"dal": "Date A Live",
	"dal 2": "Date A Live II",
	"dal 3": "Date A Live III",
	"denyuden": "Densetsu no Yuusha no Densetsu",
	"ubw": "Fate/stay night: Unlimited Blade Works",
	"kagejitsu": "Kage no Jitsuryokusha ni Naritakute!",
	"kagejitsu 2": "Kage no Jitsuryokusha ni Naritakute! 2nd Season",
	"fma": "Hagane no Renkinjutsushi",
	"fmab": "Hagane no Renkinjutsushi: Brotherhood",
	"domekano": "Domestic na Kanojo",
	"gochiusa": "Gochuumon wa Usagi desu ka?",
	"gochiusa 2": "Gochuumon wa Usagi desu ka??",
	"gochiusa 3": "Gochuumon wa Usagi desu ka? Bloom",
	"gochiusa movie": "Gochuumon wa Usagi desu ka?? Dear My Sister",
	"gochiusa ova": "Gochuumon wa Usagi desu ka?? Sing For You",
	"lycoreco": "Lycoris Recoil",
	"ngnl": "No Game No Life",
	"oretwi": "Ore, Twintail ni Narimasu.",
	"psg": "Panty & Stocking with Garterbelt",
	"bandori": "Bang Dream!",
	"bandori 2": "BanG Dream! 2nd Season",
	"bandori 3": "Bang Dream! 3rd Season",
	"bandori film": "BanG Dream! Film Live",
	"bandori film 2": "BanG Dream! Film Live 2nd Stage",
	"brr": "Blue Reflection Ray",
	"imas": "The iDOLM@STER",
	"ppgz": "Demashitaa! Powerpuff Girls Z",
	"konosuba": "Kono Subarashii Sekai ni Shukufuku o!",
	"konosuba 2": "Kono Subarashii Sekai ni Shukufuku o! 2",
	"konosuba 3": "Kono Subarashii Sekai ni Shukufuku o! 3",
	"hip whip girl": "Keijo!!!!!!!!",
	"assclass": "Ansatsu Kyoushitsu",
	"assclass 2": "Ansatsu Kyoushitsu Final Season",
	"aggretsuko": "Aggressive Retsuko",
	"aggretsuko special": "Aggressive Retsuko: We Wish You a Metal Christmas",
	"bnha": "Boku no Hero Academia",
	"boku no pico academia": "Boku no Hero Academia",
	"diy": "Do It Yourself!!",
	"kmb": "Kill Me Baby",
	"fairy fail": "Fairy Tail",
	"kkkb": "Kuma Kuma Kuma Bear",
	"kkkbp": "Kuma Kuma Kuma Bear: Punch!",
	"lwa": "Little Witch Academia",
	"lwam": "Little Witch Academia: Mahoujikake no Parade",
	"mia": "Made in Abyss",
	"mia dawn": "Made in Abyss: Fukaki Tamashii no Reimei",
	"mia golden": "Made in Abyss: Retsujitsu no Ougonkyou",
	"mia recap": "Gekijouban Soushuuhen Made in Abyss",
	"onimai": "Onii-chan wa Oshimai!",
	"pte": "Poputepipikku",
	"pte 2": "Pop Team Epic 2nd Season",
	"bgs": "Seishun Buta Yarou wa Bunny Girl Senpai no Yume o Minai",
	"sao": "Sword Art Online",
	"sao 2": "Sword Art Online II",
	"sao 3": "Sword Art Online: Alicization",
	"sao 4": "Sword Art Online: Alicization - War of Underworld",
	"sao ordinal": "Gekijouban Sword Art Online: Ordinal Scale",
	"sao movie": "Gekijouban Sword Art Online: Ordinal Scale",
	"ggo": "Sword Art Online Alternative: Gun Gale Online",
	"ggo 2": "Sword Art Online Alternative: Gun Gale Online II",
	"sao extra": "Sword Art Online: Extra Edition",
	"gits": "Koukaku Kidoutai",
	"sac": "Koukaku Kidoutai: Stand Alone Complex",
	"the * war": "Gakusen Toshi Asterisk",
	"aot": "Shingeki no Kyojin",
	"aot 2": "Shingeki no Kyojin Season 2",
	"aot 3": "Shingeki no Kyojin Season 3",
	"aot final": "Shingeki no Kyojin: The Final Season",
	"aot very final": "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
	"glub glub": "Mirai Nikki",
	"teu cu": "Teekyuu",
	"bokuyaba": "Boku no Kokoro no Yabai Yatsu",
	"the cock": "Bocchi the Rock!",
	"suuzme": "Suzume",
	"👂": "Haven't You Heard? I'm Sakamoto",
	"penis line": "Birdie Wing: Golf Girls' Story",
	"space daddy": "Space☆Dandy",
	"fate/adrian": "Fate/Zero",
}
